package reports;

import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.ColumnText;
import com.itextpdf.text.pdf.PdfPageEventHelper;
import com.itextpdf.text.pdf.PdfTemplate;
import com.itextpdf.text.pdf.PdfWriter;

public class ReportPageHelper extends PdfPageEventHelper {
    private PdfTemplate totalPagesTemplate;
    private final String headerText;
    private final String footerText;
    private final String userName;
    private final Font fontHeader = new Font(Font.FontFamily.HELVETICA, 10, Font.BOLD);
    private final Font fontFooter = new Font(Font.FontFamily.HELVETICA, 8, Font.ITALIC);
    private BaseFont baseFontFooter;

    public ReportPageHelper(String headerText, String footerText, String userName) {
        this.headerText = headerText;
        this.footerText = footerText;
        this.userName = userName;
        try {
            this.baseFontFooter = BaseFont.createFont(BaseFont.HELVETICA_OBLIQUE, BaseFont.WINANSI, BaseFont.EMBEDDED);
        } catch (Exception e) {
            System.err.println("Could not initialize BaseFont for footer: " + e.getMessage());
        }
    }

    @Override
    public void onOpenDocument(PdfWriter writer, Document document) {
        totalPagesTemplate = writer.getDirectContent().createTemplate(30, 12);
    }

    @Override
    public void onEndPage(PdfWriter writer, Document document) {
        // Draw top running header
        ColumnText.showTextAligned(writer.getDirectContent(), Element.ALIGN_CENTER, 
                new Phrase(headerText, fontHeader), (document.right() + document.left()) / 2, document.top() + 15, 0);

        // Draw bottom running footer
        String pageInfo = "Page " + writer.getPageNumber() + " of ";
        float textBaseY = document.bottom() - 20;
        
        // Left footer
        ColumnText.showTextAligned(writer.getDirectContent(), Element.ALIGN_LEFT, 
                new Phrase(footerText + " | Generated by: " + userName, fontFooter), document.left(), textBaseY, 0);

        // Right footer page number
        float rightPositionX = document.right() - 20;
        float totalPagesOffsetX = rightPositionX + 3f;
        ColumnText.showTextAligned(writer.getDirectContent(), Element.ALIGN_RIGHT, 
                new Phrase(pageInfo, fontFooter), rightPositionX, textBaseY, 0);

        // Add template for total pages after the text
        writer.getDirectContent().addTemplate(totalPagesTemplate, totalPagesOffsetX, textBaseY);
    }

    @Override
    public void onCloseDocument(PdfWriter writer, Document document) {
        totalPagesTemplate.beginText();
        if (baseFontFooter != null) {
            totalPagesTemplate.setFontAndSize(baseFontFooter, 8);
        } else {
            totalPagesTemplate.setFontAndSize(fontFooter.getCalculatedBaseFont(false), 8);
        }
        totalPagesTemplate.showText(String.valueOf(writer.getPageNumber()));
        totalPagesTemplate.endText();
    }
}
